replicaCount: 1
nameOverride: ""
fullnameOverride: ""

image:
  repository: dewms/spring-cloud-config
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  annotations: {}
  hosts: []
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}