apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    dew.ms/git-commit: '0001'
    dew.ms/scm-url: ''
    dew.ms/git-branch: ''
  labels:
    app: helloworld-frontend
    provider: dew
    version: '0001'
    group: ms.dew
  name: helloworld-frontend
  namespace: dew-test
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helloworld-frontend
      group: ms.dew
  template:
    metadata:
      annotations:
        dew.ms/git-commit: '0001'
        dew.ms/scm-url: ''
        dew.ms/git-branch: ''
      labels:
        app: helloworld-frontend
        provider: dew
        version: '0001'
        group: ms.dew
    spec:
      containers:
        - image: harbor.dew.env/dew-test/helloworld-frontend:0001
          imagePullPolicy: IfNotPresent
          name: dew-app
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
