apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    dew.idealworld.group/git-commit: "@ignore@"
    dew.idealworld.group/scm-url: "@ignore@"
  labels:
    app: helloworld-frontend
    provider: dew
    version: "@ignore@"
    group: group.idealworld.dew.devops.it
  name: helloworld-frontend
  namespace: dew-test
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helloworld-frontend
      group: group.idealworld.dew.devops.it
  template:
    metadata:
      annotations:
        dew.idealworld.group/git-commit: "@ignore@"
        dew.idealworld.group/scm-url: "@ignore@"
      labels:
        app: helloworld-frontend
        provider: dew
        version: "@ignore@"
        group: group.idealworld.dew.devops.it
    spec:
      containers:
      - image: "@ignore@"
        imagePullPolicy: IfNotPresent
        name: dew-app
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits: {}
          requests: {}
      nodeSelector:
        group: app
