apiVersion: v1
kind: Service
metadata:
  annotations:
    dew.ms/git-commit: '0001'
    dew.ms/scm-url: ''
    prometheus.io/port: '9779'
    prometheus.io/scrape: 'true'
    dew.ms/git-branch: ''
  labels:
    app: helloworld-frontend
    provider: dew
    version: '0001'
    expose: 'true'
    group: ms.dew.devops.it
  name: helloworld-frontend
  namespace: dew-test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: helloworld-frontend
    group: ms.dew.devops.it
