kind: ConfigMap
apiVersion: v1
metadata:
  name: custom-config
data:
  bootstrap.yml: |-
    spring:
      profiles:
        active: native
      security:
        user:
          name: dew
          password: override
    # This configuration must be in bootstrap file
    encrypt:
      key: sfosdfY22ddf
