apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    dew.idealworld.group/git-commit: "@ignore@"
    dew.idealworld.group/scm-url: "@ignore@"
    sidecar.jaegertracing.io/inject: 'true'
  labels:
    app: compute
    provider: dew
    version: "@ignore@"
    group: group.idealworld.dew.devops.it
  name: compute
  namespace: dew-prod
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: compute
      group: group.idealworld.dew.devops.it
  template:
    metadata:
      annotations:
        dew.idealworld.group/git-commit: "@ignore@"
        dew.idealworld.group/scm-url: "@ignore@"
        sidecar.jaegertracing.io/inject: 'true'
      labels:
        app: compute
        provider: dew
        version: "@ignore@"
        group: group.idealworld.dew.devops.it
    spec:
      containers:
      - env:
        - name: JAVA_DEBUG_OPTIONS
          value: ' -Dspring.profiles.active=test -Dserver.port=9000'
        - name: JAVA_OPTIONS
          value: ' -Dspring.profiles.active=prod -Dserver.port=8080 -Dopentracing.jaeger.log-spans=false
            -Dopentracing.jaeger.probabilistic-sampler.sampling-rate=0.1 -Dopentracing.spring.web.skip-pattern=/api-docs.*|/swagger.*|.*\\.png|.*\\.css|.*\\.js|.*\\.html|/favicon.ico|/hystrix.stream|/actuator.*
            -Dmanagement.endpoints.web.exposure.include=* -Dmanagement.metrics.tags.application=compute'
        image: "@ignore@"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
        name: dew-app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          limits: {}
          requests: {}
      nodeSelector:
        group: app
