apiVersion: v1
kind: Service
metadata:
  annotations:
    dew.ms/git-commit: '0001'
    dew.ms/scm-url: ''
    prometheus.io/port: '9779'
    prometheus.io/scrape: 'true'
    sidecar.jaegertracing.io/inject: 'true'
  labels:
    app: todo-compute
    provider: dew
    version: '0001'
    expose: 'true'
    group: ms.dew.devops.it
  name: todo-compute
  namespace: dew-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: todo-compute
    group: ms.dew.devops.it
