apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    dew.ms/git-commit: '0001'
    dew.ms/scm-url: ''
    sidecar.jaegertracing.io/inject: 'true'
  labels:
    app: todo-kernel
    provider: dew
    version: '0001'
    group: ms.dew.devops.it
  name: todo-kernel
  namespace: dew-uat
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: todo-kernel
      group: ms.dew.devops.it
  template:
    metadata:
      annotations:
        dew.ms/git-commit: '0001'
        dew.ms/scm-url: ''
        sidecar.jaegertracing.io/inject: 'true'
      labels:
        app: todo-kernel
        provider: dew
        version: '0001'
        group: ms.dew.devops.it
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: ' -Dspring.profiles.active=uat -Dserver.port=8080 -Dopentracing.jaeger.log-spans=false
            -Dmanagement.endpoints.web.exposure.include=* -Dmetrics.tags:application=${spring.application.name}'
        image: harbor.trc.com/dew-uat/todo-kernel:0001
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
        name: dew-app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          limits:
            memory: 1Gi
            cpu: 800m
          requests: {}
      nodeSelector:
        group: app
