apiVersion: v1
kind: Service
metadata:
  annotations:
    dew.ms/git-commit: "@ignore@"
    dew.ms/scm-url: "@ignore@"
    sidecar.jaegertracing.io/inject: 'true'
  labels:
    app: kernel
    provider: dew
    version: "@ignore@"
    expose: 'true'
    group: ms.dew.devops.it
  name: kernel
  namespace: dew-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kernel
    group: ms.dew.devops.it
