spring:
  application:
    name: web-example

server:
  port: 80 # http端口号
  tomcat:
    max-threads: 1000

dew:
  basic:
    name: web
    version: 1.0
    desc: desc
    web-site: www.tairanchina.com
    doc:
      base-package: com.tairanchina # API文档路径

logging:
  path: ./logs

management:
  security:
    enabled: false
  context-path: /management-admin
