apiVersion: v1
kind: Service
metadata:
  annotations:
    dew.idealworld.group/git-commit: "@ignore@"
    dew.idealworld.group/scm-url: "@ignore@"
  labels:
    app: todo-frontend
    provider: dew
    version: "@ignore@"
    expose: 'true'
    group: group.idealworld.dew.devops.it
  name: todo-frontend
  namespace: dew-prod
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: todo-frontend
    group: group.idealworld.dew.devops.it
