apiVersion: v1
kind: Service
metadata:
  annotations:
    dew.idealworld.group/git-commit: "@ignore@"
    dew.idealworld.group/scm-url: "@ignore@"
    sidecar.jaegertracing.io/inject: 'true'
  labels:
    app: notifier
    provider: dew
    version: "@ignore@"
    expose: 'true'
    group: group.idealworld.dew.devops.it
  name: notifier
  namespace: dew-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: notifier
    group: group.idealworld.dew.devops.it
