apiVersion: v1
kind: Service
metadata:
  annotations:
    dew.ms/git-commit: '0001'
    dew.ms/scm-url: ''
    sidecar.jaegertracing.io/inject: 'true'
  labels:
    app: notifier
    provider: dew
    version: '0001'
    expose: 'true'
    group: ms.dew.devops.it
  name: notifier
  namespace: dew-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: notifier
    group: ms.dew.devops.it
